# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: composer install 
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: 
          name: Execute Tests
          command : composer run tests
  deploy:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run:
          name: Install DPL Gem
          command: gem install dpl
      - run: 
          name: Deploy Demo Branch
          command: |
            git fetch
            git checkout demo
            dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
